services:
  web:
    container_name: invoice-server
    build:
      context: .
      dockerfile: Dockerfile
    command: dev
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "secret"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_USE_TLS: "False"

    links:
      - postgres
#      - minio
      - mailhog
    depends_on:
      - postgres
#      - minio
      - mailhog
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - .datastore/postgres:/var/lib/postgresql/data

#  minio:
#    image: minio/minio
#    environment:
#      MINIO_ROOT_USER: "minio_root_user"
#      MINIO_ROOT_PASSWORD: "minio_root_password"
#      MINIO_SERVER_URL: "http://minio:9000"
#      MINIO_BROWSER_REDIRECT_URL: "https://minio.glm.local"
#      MINIO_CONSOLE_ADDRESS: ":9001"
#      MINIO_ADDRESS: ":9000"
#    volumes:
#      - .datastore/minio:/data
#    expose:
#      - "9000"
#      - "9001"
#    command: server /data
#    networks:
#      - glm-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3

#  minio-mc:
#    image: minio/mc
#    restart: no
#    entrypoint: >
#      /bin/sh -c "
#        while ! curl -I http://minio:9000/minio/health/live; do echo 'Wait minio to startup...' && sleep 0.1; done; sleep 5;
#        mc alias set minio http://minio:9000 minio_root_user minio_root_password;
#        mc mb minio/glm-static;
#        mc mb minio/glm-media;
#        mc anonymous set public minio/glm-static;
#        mc anonymous set public minio/glm-media;
#        exit 0;
#      "
#    depends_on:
#      - minio
#    networks:
#      - glm-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
