services:
  web:
    container_name: invoice-server
    build:
      context: .
      dockerfile: Dockerfile
    command: dev
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "secret"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_USE_TLS: "False"

    links:
      - postgres
#      - minio
      - mailhog
    depends_on:
      - postgres
#      - minio
      - mailhog
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - .datastore/postgres:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
