[tool.poetry]
name = "invoice-manager"
version = "0.1.0"
description = ""
authors = ["Wioletta Wajda <wioletta.wajda@devsoft.pl>"]
readme = "README.md"
packages = [{include = "invoice_manager"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.7"
celery = "^5.2.7"
django-environ = "^0.10.0"
djangorestframework = "^3.14.0"
djangorestframework-filters = "^0.11.1"
black = "^23.3.0"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''

(
  /(
    | \.git
    | migrations
    | venv
    | \.env
  )/
)
'''

[tool.isort]
skip = [".git", "migrations", "venv", ".env"]
