[tool.poetry]
name = "invoice-manager"
version = "0.1.0"
description = ""
authors = ["Wioletta Wajda <wioletta.wajda@devsoft.pl>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.11"
celery = "^5.2.7"
django-environ = "^0.10.0"
djangorestframework = "^3.14.0"
black = "24.3.0"
isort = "^5.12.0"
django-filter = "^23.1"
django-extensions = "^3.2.1"
xhtml2pdf = "^0.2.9"
num2words = "^0.5.12"
pytest-django = "^4.5.2"
coverage = "^7.2.5"
factory-boy = "^3.2.1"
requests = "^2.31.0"
redis = "^4.6.0"
parameterized = "^0.9.0"
django-factory-boy-generator = "^1.0.4"
django-cors-headers = "^4.3.1"
django-storages = "^1.14.2"
gunicorn = "^21.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''

(
  /(
    | \.git
    | migrations
    | venv
    | \.env
  )/
)
'''

[tool.isort]
skip = [".git", "migrations", "venv", ".env"]
