# Generated by Django 4.1.7 on 2023-04-10 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("currencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=30, verbose_name="Invoice number"),
                ),
                (
                    "invoice_type",
                    models.IntegerField(
                        choices=[(0, "Sales"), (1, "Purchase")],
                        verbose_name="Invoice type",
                    ),
                ),
                (
                    "recurring_frequency",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Weekly"),
                            (1, "Biweekly"),
                            (2, "Monthly"),
                            (3, "Three month"),
                        ],
                        null=True,
                        verbose_name="Recurring_frequency",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Recurring"),
                ),
                (
                    "create_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Create date"
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sale date"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Payment date"
                    ),
                ),
                (
                    "payment_method",
                    models.IntegerField(
                        choices=[(0, "Transfer"), (1, "Cash")],
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Account number",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="currencies.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
