# Generated by Django 4.2.5 on 2023-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_settled",
            field=models.BooleanField(default=False, verbose_name="Settled"),
        ),
    ]
