# Generated by Django 4.2 on 2023-05-07 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0004_alter_currency_code_alter_currency_is_my_currency"),
        ("companies", "0004_alter_company_options_alter_company_address_and_more"),
        ("invoices", "0002_invoice_is_my_invoice_alter_invoice_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoice",
                to="companies.company",
                verbose_name="Client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Numer konta"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="create_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data utworzenia"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="currencies.currency",
                verbose_name="Waluta",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=30, verbose_name="Numer faktury"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.IntegerField(
                choices=[(0, "Sprzedaż"), (1, "Zakupy")], verbose_name="Typ faktury"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_my_invoice",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Czt moja faktura"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Powtarza się"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data płatności"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.IntegerField(
                choices=[(0, "Przelew"), (1, "Gotówka")],
                verbose_name="Rodzaj płatności",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="recurring_frequency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Co tydzień"),
                    (1, "Co dwa tygodnie"),
                    (2, "Co miesiąc"),
                    (3, "Co trzy miesiące"),
                ],
                null=True,
                verbose_name="Cykliczna częstotliwość",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data sprzedaży"
            ),
        ),
    ]
