# Generated by Django 4.2.5 on 2023-09-24 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoice_is_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="settlement_period",
            field=models.IntegerField(
                choices=[(0, "Current"), (1, "Next"), (2, "In 2 months")],
                default=0,
                verbose_name="Settlement period",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Z ]{15,32}$",
                        "Wpisz numer rachunku bez znaków specjalnych składający się z min. 15 znaków",
                    )
                ],
                verbose_name="Numer konta",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_settled",
            field=models.BooleanField(default=False, verbose_name="Rozliczona"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="recurring_frequency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Co tydzień"),
                    (1, "Co dwa tygodnie"),
                    (2, "Co miesiąc"),
                    (3, "Co trzy miesiące"),
                ],
                null=True,
                verbose_name="Recurring frequency",
            ),
        ),
    ]
