# Generated by Django 4.2 on 2023-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_alter_company_options_alter_company_address_and_more"),
        ("invoices", "0003_invoice_client_alter_invoice_account_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["sale_date"]},
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoice",
                to="companies.company",
                verbose_name="Kontrahent",
            ),
        ),
    ]
