# Generated by Django 4.0.1 on 2022-01-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_company_apartment_number_company_street_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default=1, max_length=20, verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
