# Generated by Django 4.2.5 on 2023-09-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoice_settlement_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="settlement_period",
        ),
        migrations.AddField(
            model_name="invoice",
            name="settlement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Settlement_date"
            ),
        ),
    ]
