# Generated by Django 4.2.1 on 2023-06-03 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoice_options_alter_invoice_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_my_invoice",
        ),
    ]
