# Generated by Django 4.0.1 on 2022-01-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_company_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Unit'),
        ),
    ]
