# Generated by Django 4.2.5 on 2023-09-26 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_company_city_alter_company_nip_and_more"),
        ("invoices", "0005_remove_invoice_settlement_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoice",
                to="companies.company",
                verbose_name="Kontrahent",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+/[0-9]{4}$",
                        "Numer faktury należy wprowadzać cyfrowo, wyłącznie w formacie numer/rrrr",
                    )
                ],
                verbose_name="Numer faktury",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data płatności"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Przelew"), (1, "Gotówka")],
                null=True,
                verbose_name="Rodzaj płatności",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data sprzedaży"
            ),
        ),
    ]
