# Generated by Django 4.2.5 on 2023-10-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_alter_invoice_client_alter_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="settlement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Settlement date"
            ),
        ),
    ]
