# Generated by Django 4.2.4 on 2023-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_alter_invoice_options_alter_invoice_is_recurring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_day",
            field=models.IntegerField(default=0, verbose_name="Payment day"),
        ),
    ]
