# Generated by Django 4.2.4 on 2023-08-16 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0007_invoice_payment_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="payment_day",
        ),
    ]
