# Generated by Django 4.0.1 on 2022-01-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ]
