# Generated by Django 4.2.5 on 2023-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0007_alter_invoice_settlement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Pdf file"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="recurring_frequency",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Co tydzień"),
                    (1, "Co dwa tygodnie"),
                    (2, "Co miesiąc"),
                    (3, "Co trzy miesiące"),
                ],
                null=True,
                verbose_name="Cykliczna częstotliwość",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="settlement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data rozliczenia"
            ),
        ),
    ]
