# Generated by Django 4.2.4 on 2023-08-23 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_remove_invoice_payment_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Z ]{15,32}$",
                        "Enter account number without special characters",
                    )
                ],
                verbose_name="Numer konta",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+/[0-9]{4}$",
                        "Enter invoice number in numbers only in format number/yyyy",
                    )
                ],
                verbose_name="Numer faktury",
            ),
        ),
    ]
