# Generated by Django 4.2.5 on 2023-10-01 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoices",
            "0008_invoice_pdf_file_alter_invoice_recurring_frequency_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="pdf_file",
            new_name="invoice_file",
        ),
    ]
