# Generated by Django 4.2.4 on 2023-08-23 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_alter_invoice_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Z ]{15,32}$",
                        "Enter account number with minimum 15 character without special characters",
                    )
                ],
                verbose_name="Numer konta",
            ),
        ),
    ]
