# Generated by Django 4.2.5 on 2023-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_rename_pdf_file_invoice_invoice_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Invoice file"
            ),
        ),
    ]
