# Generated by Django 4.0.1 on 2022-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Liter'), (2, 'Kilometer'), (3, 'Hour'), (4, 'Item')], default=1, verbose_name='Type oof unit'),
            preserve_default=False,
        ),
    ]
