# Generated by Django 4.2.4 on 2023-09-03 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_alter_invoice_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Z ]{15,32}$",
                        "Wpisz numer rachunku składający się z min. 15 znaków bez znaków specjalnych",
                    )
                ],
                verbose_name="Numer konta",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]+/[0-9]{4}$",
                        "Numer faktury należy wprowadzać cyfrowo, wyłącznie w formacie numer/rrrr",
                    )
                ],
                verbose_name="Numer faktury",
            ),
        ),
    ]
