# Generated by Django 4.2.5 on 2023-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_alter_invoice_invoice_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Numer konta"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Numer faktury"
            ),
        ),
    ]
