# Generated by Django 4.2.5 on 2023-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_alter_invoice_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Typ faktury"
            ),
        ),
    ]
