# Generated by Django 4.0.1 on 2022-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Liter'), (2, 'Kilometer'), (3, 'Hour'), (4, 'Item')], verbose_name='Type of unit'),
        ),
    ]
