# Generated by Django 4.2.5 on 2023-11-23 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0010_delete_summaryrecipient"),
        ("invoices", "0012_alter_invoice_invoice_file"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("invoice_number", "company")},
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
    ]
