# Generated by Django 4.0.1 on 2022-01-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(max_length=12, unique=True, verbose_name='NIP'),
        ),
    ]
