# Generated by Django 4.2.5 on 2023-11-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_alter_person_email_alter_person_phone_number"),
        ("invoices", "0013_alter_invoice_unique_together_remove_invoice_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="persons.person",
                verbose_name="Person",
            ),
        ),
    ]
