# Generated by Django 4.0.1 on 2022-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_company_nip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='street',
            new_name='street_and_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_number',
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Symbol'),
        ),
    ]
