# Generated by Django 4.2.5 on 2023-12-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0005_alter_person_options"),
        ("invoices", "0014_invoice_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is paid"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="persons.person",
                verbose_name="Konsument",
            ),
        ),
    ]
