# Generated by Django 4.0.1 on 2022-01-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_remove_company_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
