# Generated by Django 4.2.5 on 2024-01-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0019_alter_correctioninvoice_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctioninvoice",
            name="correction_invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_invoice",
                to="invoices.invoice",
                verbose_name="Correction Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="correctioninvoice",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correction_invoice",
                to="invoices.invoice",
                verbose_name="Faktura",
            ),
        ),
    ]
