# Generated by Django 4.2.5 on 2024-01-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0010_delete_summaryrecipient"),
        ("currencies", "0005_alter_exchangerate_options"),
        ("invoices", "0020_alter_correctioninvoice_correction_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionInvoiceRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "correction invoices",
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoices",
                to="companies.company",
                verbose_name="Kontrahent",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="companies.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="currencies.currency",
                verbose_name="Waluta",
            ),
        ),
        migrations.DeleteModel(
            name="CorrectionInvoice",
        ),
        migrations.AddField(
            model_name="correctioninvoicerelation",
            name="correction_invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correction_invoice_relation",
                to="invoices.invoice",
                verbose_name="Correction Invoice",
            ),
        ),
        migrations.AddField(
            model_name="correctioninvoicerelation",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_invoice_relation",
                to="invoices.invoice",
                verbose_name="Faktura",
            ),
        ),
    ]
