# Generated by Django 4.2.5 on 2024-01-07 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0021_correctioninvoicerelation_alter_invoice_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctioninvoicerelation",
            options={"verbose_name_plural": "correction invoices relation"},
        ),
    ]
