# Generated by Django 4.2.5 on 2024-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0023_alter_correctioninvoicerelation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Gross_amount"
            ),
        ),
    ]
