# Generated by Django 4.2.5 on 2024-01-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0024_invoice_gross_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Rok")),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Kwota brutto"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Kwota netto"
            ),
        ),
    ]
