# Generated by Django 4.2.5 on 2024-02-01 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0025_year_alter_invoice_gross_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["-year"]},
        ),
        migrations.AddField(
            model_name="year",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
    ]
