# Generated by Django 4.0.1 on 2022-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vatrate',
            options={'ordering': ['rate']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Recurring'),
        ),
    ]
