# Generated by Django 4.0.1 on 2022-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_alter_vatrate_options_invoice_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='recurring_frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Weekly'), (1, 'Biweekly'), (2, 'Monthly'), (3, 'Three month')], null=True, verbose_name='Recurring_frequency'),
        ),
    ]
