# Generated by Django 4.1.7 on 2023-04-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0027_invoice_recurring_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="regon",
            field=models.CharField(
                max_length=12, null=True, unique=True, verbose_name="Regon"
            ),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Country"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.country",
                verbose_name="Country",
            ),
        ),
    ]
