# Generated by Django 4.1.7 on 2023-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0028_company_regon_country_company_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="unit",
        ),
        migrations.AddField(
            model_name="item",
            name="pkwiu",
            field=models.CharField(max_length=50, null=True, verbose_name="PWKiU"),
        ),
    ]
