# Generated by Django 4.2.10 on 2024-03-06 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0028_remove_invoice_recurring_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data płatności"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data sprzedaży"
            ),
        ),
    ]
