# Generated by Django 4.1.7 on 2023-04-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("invoices", "0029_remove_item_unit_item_pkwiu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="user",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
