# Generated by Django 4.2.10 on 2024-03-12 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0029_alter_invoice_payment_date_alter_invoice_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="settlement_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data rozliczenia"
            ),
        ),
    ]
