# Generated by Django 4.2.11 on 2024-07-25 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "currencies",
            "0006_alter_currency_options_alter_exchangerate_options_and_more",
        ),
        ("persons", "0006_alter_person_options_alter_person_address_and_more"),
        ("companies", "0011_alter_company_options_alter_company_address_and_more"),
        ("invoices", "0030_alter_invoice_settlement_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctioninvoicerelation",
            options={"verbose_name_plural": "correction invoices relation"},
        ),
        migrations.AlterField(
            model_name="correctioninvoicerelation",
            name="correction_invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correction_invoice_relation",
                to="invoices.invoice",
                verbose_name="Correction Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="correctioninvoicerelation",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_invoice_relation",
                to="invoices.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Account number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_invoices",
                to="companies.company",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="create_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Create date"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="currencies.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Gross_amount"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Invoice file"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Invoice number"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.IntegerField(
                choices=[(0, "Sales"), (1, "Purchase")], verbose_name="Invoice type"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_last_day",
            field=models.BooleanField(default=False, verbose_name="Last day in month"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Recurring"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="is_settled",
            field=models.BooleanField(default=False, verbose_name="Settled"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Net amount"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Payment date"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "Transfer"), (1, "Cash")],
                null=True,
                verbose_name="Payment method",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="persons.person",
                verbose_name="Person",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="sale_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Sale date"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="settlement_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Settlement date"
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Year"),
        ),
    ]
