# Generated by Django 5.2.1 on 2026-01-06 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0032_alter_invoice_options_alter_year_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="year",
            unique_together={("year", "user")},
        ),
    ]
