---
apiVersion: v1
kind: Service
metadata:
  name: invoice-factory-svc
  namespace: apps
  labels:
    app: invoice-factory
spec:
  selector:
    app: invoice-factory
  ports:
    - name: http
      port: 8000