---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: invoice-factory-tls
  namespace: apps
  labels:
    app: invoice-factory
spec:
  commonName: invoice-factory.devsoft.pl
  secretName: invoice-factory-tls
  dnsNames:
    - invoice-factory.devsoft.pl
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
