# Generated by Django 4.2.5 on 2023-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=30, verbose_name="Kraj"),
        ),
    ]
