# Generated by Django 4.2.4 on 2023-08-07 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("countries", "0005_alter_country_options_remove_country_is_my_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["country"], "verbose_name_plural": "Kraje"},
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("country", "user")},
        ),
    ]
