# Generated by Django 4.2.4 on 2023-08-16 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0006_alter_country_options_alter_country_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["country"], "verbose_name_plural": "kraje"},
        ),
    ]
