# Generated by Django 4.2.4 on 2023-09-03 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0010_alter_country_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z ]{2,}$", "Podaj kraj tylko literami"
                    )
                ],
                verbose_name="Kraj",
            ),
        ),
    ]
