# Generated by Django 4.2.4 on 2023-09-05 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z]{3}$", "Wprowadź trzyliterowy kod kraju"
                            )
                        ],
                        verbose_name="Kod waluty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "waluty",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Kurs kupna",
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Kurs sprzedaży",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="currencies.currency",
                        verbose_name="Waluta",
                    ),
                ),
            ],
        ),
    ]
