# Generated by Django 4.1.7 on 2023-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
    ]
