# Generated by Django 4.2.5 on 2023-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Kod waluty"),
        ),
    ]
