# Generated by Django 4.2 on 2023-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0003_currency_is_my_currency_alter_currency_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="is_my_currency",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Czy moja waluta"
            ),
        ),
    ]
