# Generated by Django 4.2.1 on 2023-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0004_alter_currency_code_alter_currency_is_my_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="is_my_currency",
        ),
    ]
