# Generated by Django 4.2.3 on 2023-08-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0005_remove_currency_is_my_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["code"], "verbose_name_plural": "currencies"},
        ),
        migrations.AddField(
            model_name="currency",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Exchange rate"
            ),
        ),
    ]
