# Generated by Django 4.2.11 on 2024-07-25 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currencies", "0005_alter_exchangerate_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["code"], "verbose_name_plural": "currencies"},
        ),
        migrations.AlterModelOptions(
            name="exchangerate",
            options={"verbose_name_plural": "exchange rates"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="buy_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Buy rate"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_rates",
                to="currencies.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="sell_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Sell rate"
            ),
        ),
    ]
