# Generated by Django 4.2.3 on 2023-08-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0007_remove_currency_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Buy rate",
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Buy rate",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currencies.currency",
                        verbose_name="Waluta",
                    ),
                ),
            ],
        ),
    ]
