# Generated by Django 4.2.4 on 2023-08-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currencies", "0008_exchangerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_rates",
                to="currencies.currency",
                verbose_name="Waluta",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="sell_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Sell rate"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currency",
            unique_together={("code", "user")},
        ),
    ]
