# Generated by Django 4.2.4 on 2023-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0009_alter_exchangerate_currency_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["code"], "verbose_name_plural": "waluty"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Kod waluty"),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="buy_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Kurs kupna"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="sell_rate",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=5, verbose_name="Kurs sprzedaży"
            ),
        ),
    ]
