# Generated by Django 4.2.4 on 2023-08-17 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0010_alter_currency_options_alter_currency_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]{3}$", "Enter country three letter code"
                    )
                ],
                verbose_name="Kod waluty",
            ),
        ),
    ]
