# Generated by Django 4.2.4 on 2023-09-03 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0011_alter_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]{3}$", "Wprowadź trzyliterowy kod kraju"
                    )
                ],
                verbose_name="Kod waluty",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="date",
            field=models.DateField(verbose_name="Data"),
        ),
    ]
