# Generated by Django 4.2.4 on 2023-09-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa")),
                (
                    "pkwiu",
                    models.CharField(max_length=50, null=True, verbose_name="PWKiU"),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Ilość")),
                (
                    "net_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Kwota netto"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                        verbose_name="Faktura",
                    ),
                ),
            ],
            options={
                "ordering": ["vat"],
            },
        ),
    ]
