# Generated by Django 4.2 on 2023-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoice_options_alter_invoice_client"),
        ("items", "0002_item_is_my_item_alter_item_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Ilość"),
        ),
        migrations.AlterField(
            model_name="item",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
                verbose_name="Faktura",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_my_item",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Czy moja pozycja"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="item",
            name="net_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Kwota netto"
            ),
        ),
    ]
