# Generated by Django 4.2.1 on 2023-06-03 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_alter_item_amount_alter_item_invoice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_my_item",
        ),
    ]
