# Generated by Django 4.2.11 on 2024-07-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vat_rates", "0003_alter_vatrate_rate_alter_vatrate_user"),
        ("invoices", "0031_alter_correctioninvoicerelation_options_and_more"),
        ("items", "0004_alter_item_net_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="item",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="net_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Net price"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="vat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="vat_rates.vatrate",
                verbose_name="Vat",
            ),
        ),
    ]
