# Generated by Django 4.2.4 on 2023-08-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vat_rates", "0006_alter_vatrate_rate"),
        ("items", "0004_remove_item_is_my_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["vat"]},
        ),
        migrations.AlterField(
            model_name="item",
            name="vat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="vat_rates.vatrate",
                verbose_name="VAT",
            ),
        ),
    ]
