# Generated by Django 4.2.11 on 2024-08-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vat_rates", "0003_alter_vatrate_rate_alter_vatrate_user"),
        ("items", "0005_alter_item_amount_alter_item_invoice_alter_item_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="vat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="vat_rates.vatrate",
                verbose_name="Vat",
            ),
        ),
    ]
