# Generated by Django 4.2.5 on 2023-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountants", "0003_accountant_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountant",
            options={"verbose_name_plural": "księgowi"},
        ),
        migrations.AlterField(
            model_name="accountant",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nazwa"
            ),
        ),
    ]
