# Generated by Django 4.2.5 on 2023-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountants", "0004_alter_accountant_options_alter_accountant_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountant",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
