# Generated by Django 4.2.5 on 2023-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountants", "0006_alter_accountant_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountant",
            name="name",
            field=models.CharField(default=None, max_length=100, verbose_name="Nazwa"),
        ),
    ]
