# Generated by Django 4.2.5 on 2023-11-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0010_delete_summaryrecipient"),
        ("accountants", "0007_alter_accountant_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountant",
            name="user",
        ),
        migrations.AddField(
            model_name="accountant",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_recipient",
                to="companies.company",
                verbose_name="Firma",
            ),
            preserve_default=False,
        ),
    ]
