# Generated by Django 4.2.11 on 2024-07-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_options_alter_company_address_and_more"),
        ("accountants", "0009_alter_accountant_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountant",
            options={"verbose_name_plural": "accountants"},
        ),
        migrations.AlterField(
            model_name="accountant",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_recipient",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="accountant",
            name="name",
            field=models.CharField(default=None, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="accountant",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone number"
            ),
        ),
    ]
