# Generated by Django 4.1.7 on 2023-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.CharField(max_length=12, verbose_name="NIP"),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.CharField(max_length=12, null=True, verbose_name="Regon"),
        ),
    ]
