# Generated by Django 4.1.7 on 2023-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_nip_alter_company_regon"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_my_company",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is my company"
            ),
        ),
    ]
