# Generated by Django 4.2 on 2023-05-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0004_alter_country_country_alter_country_is_my_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_company_is_my_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "firmy"},
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(max_length=60, verbose_name="Miasto"),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="countries.country",
                verbose_name="Kraj",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Adres e-mail"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_my_company",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Czy moja firma"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numer telefonu"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="zip_code",
            field=models.CharField(max_length=10, verbose_name="Kod pocztowy"),
        ),
    ]
