# Generated by Django 4.2.4 on 2023-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
