# Generated by Django 4.2.4 on 2023-08-07 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_alter_company_options_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "firmy"},
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("nip", "regon", "user")},
        ),
    ]
