# Generated by Django 4.2.4 on 2023-08-18 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_company_options_alter_company_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]*$", "Enter the tax ID without special characters"
                    )
                ],
                verbose_name="NIP",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.CharField(
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "Enter regon in numbers only"
                    )
                ],
                verbose_name="Regon",
            ),
        ),
    ]
