# Generated by Django 4.2.5 on 2023-10-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_city_alter_company_nip_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthSummaryRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Description"),
                ),
                ("day", models.IntegerField(verbose_name="Day of send")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "settlement_types",
                    models.IntegerField(
                        choices=[(0, "Co miesiąc"), (1, "Quarterly")],
                        verbose_name="settlement_types",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_summary_recipient",
                        to="companies.company",
                        verbose_name="Firma",
                    ),
                ),
            ],
        ),
    ]
