# Generated by Django 4.2.5 on 2023-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_monthsummaryrecipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthsummaryrecipient",
            name="day",
            field=models.IntegerField(verbose_name="Dzień wysłania"),
        ),
        migrations.AlterField(
            model_name="monthsummaryrecipient",
            name="description",
            field=models.CharField(max_length=50, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="monthsummaryrecipient",
            name="settlement_types",
            field=models.IntegerField(
                choices=[(0, "Co miesiąc"), (1, "Kwartalnie")],
                verbose_name="Rodzaj rozliczenia",
            ),
        ),
    ]
