# Generated by Django 4.2.4 on 2023-08-23 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_alter_company_city_alter_company_nip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(
                max_length=60,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z ]+$", "Wpisz miasto tylko literami"
                    )
                ],
                verbose_name="Miasto",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]{8,16}$",
                        "Enter the tax ID without special characters with minimum 8 character",
                    )
                ],
                verbose_name="NIP",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{9,}$", "Wprowadź numer telefonu tylko cyframi"
                    )
                ],
                verbose_name="Numer telefonu",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="regon",
            field=models.CharField(
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9]{9}|[0-9]{14})$",
                        "Enter regon in numbers only with minimum 9 character",
                    )
                ],
                verbose_name="Regon",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="zip_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{2}-[0-9]{3}$",
                        "Kod pocztowy w liczbach tylko w formacie xx-xxx",
                    )
                ],
                verbose_name="Kod pocztowy",
            ),
        ),
    ]
