# Generated by Django 4.2.5 on 2023-11-02 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_summaryrecipient_delete_monthsummaryrecipient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummaryRecipient",
        ),
    ]
