# Generated by Django 5.2.1 on 2026-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_options_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="nip",
            field=models.CharField(max_length=20, verbose_name="NIP"),
        ),
        migrations.AlterField(
            model_name="company",
            name="zip_code",
            field=models.CharField(max_length=15, verbose_name="ZIP Code"),
        ),
    ]
