# Generated by Django 5.2.1 on 2026-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_alter_company_nip_alter_company_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ksef_last_fetched_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="KSeF last fetched at"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="ksef_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="KSeF token"
            ),
        ),
    ]
