# Generated by Django 5.2.1 on 2026-04-30 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_company_ksef_last_fetched_at_company_ksef_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Created at",
            ),
        ),
    ]
