# Generated by Django 5.2.1 on 2026-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_company_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ksef_last_fetched_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="KSeF last fetched at"
            ),
        ),
    ]
