# Generated by Django 4.1.7 on 2023-04-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(verbose_name="Rate"),
        ),
    ]
