# Generated by Django 4.2.5 on 2023-10-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(verbose_name="Stawka VAT"),
        ),
    ]
