# Generated by Django 4.2.11 on 2024-07-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vat_rates", "0002_alter_vatrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(verbose_name="Rate"),
        ),
        migrations.AlterField(
            model_name="vatrate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
