# Generated by Django 5.1.3 on 2024-12-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vat_rates", "0003_alter_vatrate_rate_alter_vatrate_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vatrate",
            options={"ordering": ["rate"], "verbose_name_plural": "vat rates"},
        ),
    ]
