# Generated by Django 4.2.4 on 2023-08-07 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vat_rates", "0004_remove_vatrate_is_my_vat_alter_vatrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(verbose_name="Wskaźnik"),
        ),
        migrations.AlterUniqueTogether(
            name="vatrate",
            unique_together={("rate", "user")},
        ),
    ]
