# Generated by Django 4.2.4 on 2023-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat_rates", "0005_alter_vatrate_rate_alter_vatrate_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(verbose_name="Stawka VAT"),
        ),
    ]
