# Generated by Django 4.2.4 on 2023-08-17 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat_rates", "0006_alter_vatrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatrate",
            name="rate",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(99)],
                verbose_name="Stawka VAT",
            ),
        ),
    ]
