# Generated by Django 4.2.5 on 2023-11-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("countries", "0003_alter_country_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=75, verbose_name="Imię")),
                ("last_name", models.CharField(max_length=75, verbose_name="Nazwisko")),
                ("address", models.CharField(max_length=100, verbose_name="Adres")),
                (
                    "zip_code",
                    models.CharField(max_length=10, verbose_name="Kod pocztowy"),
                ),
                ("city", models.CharField(max_length=60, verbose_name="Miasto")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numer telefonu"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                        verbose_name="Kraj",
                    ),
                ),
            ],
        ),
    ]
