# Generated by Django 4.2.5 on 2023-11-23 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_person_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "firmy"},
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={
                ("first_name", "last_name", "address", "zip_code", "city")
            },
        ),
    ]
