# Generated by Django 4.2.5 on 2023-11-23 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0004_alter_person_options_alter_person_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name"], "verbose_name_plural": "firmy"},
        ),
    ]
