# Generated by Django 5.1 on 2024-09-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0008_alter_person_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name"], "verbose_name_plural": "persons"},
        ),
    ]
