# Generated by Django 5.2.1 on 2026-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0009_alter_person_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="nip",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NIP"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="zip_code",
            field=models.CharField(max_length=15, verbose_name="ZIP Code"),
        ),
    ]
