# Generated by Django 4.2.5 on 2023-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summary_recipients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryrecipient",
            name="final_call",
            field=models.BooleanField(default=False, verbose_name="Final call"),
        ),
    ]
