# Generated by Django 4.2.5 on 2023-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("summary_recipients", "0002_summaryrecipient_final_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaryrecipient",
            name="final_call",
            field=models.BooleanField(
                default=False, verbose_name="Ostateczne rozliczenie"
            ),
        ),
    ]
