# Generated by Django 4.2.11 on 2024-07-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_options_alter_company_address_and_more"),
        ("summary_recipients", "0003_alter_summaryrecipient_final_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaryrecipient",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_recipients",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="summaryrecipient",
            name="day",
            field=models.IntegerField(verbose_name="Day of send"),
        ),
        migrations.AlterField(
            model_name="summaryrecipient",
            name="description",
            field=models.CharField(max_length=50, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="summaryrecipient",
            name="final_call",
            field=models.BooleanField(default=False, verbose_name="Final call"),
        ),
        migrations.AlterField(
            model_name="summaryrecipient",
            name="settlement_types",
            field=models.IntegerField(
                choices=[(0, "Monthly"), (1, "Quarterly")],
                verbose_name="Settlement types",
            ),
        ),
    ]
