# Generated by Django 5.1 on 2024-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary_recipients", "0005_summaryrecipient_is_last_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaryrecipient",
            name="day",
            field=models.PositiveIntegerField(verbose_name="Day of send"),
        ),
    ]
