---
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: [ self-hosted, linux, x64 ]
    concurrency: release
    container:
      image: izabelak/actions-builder:latest
      env:
        NODE_ENV: development

    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      # install requirements
      - name: Install requirements
        run: poetry install --only semver

      # semantic release
      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@devsoft.pl"

          # run semantic-release
          poetry run semantic-release version
          poetry run semantic-release publish