---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: [ self-hosted, linux, x64 ]
    container:
      image: izabelak/actions-builder:latest

    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - run: poetry install --no-interaction --no-root

      - run: poetry install --no-interaction

      - name: Pytest
        env:
          SECRET_KEY: "abc"
          DATABASE_URL: "sqlite://test.db"
        run: |
          poetry run python manage.py compilemessages
          poetry run python manage.py test
